Import Libraries

In [ ]:
import pandas as pd
import sqlite3
import json

Import Tables

In [ ]:
customers = pd.read_csv("customers.csv")
accounts = pd.read_csv("accounts.csv")
transactions = pd.read_csv("transactions.csv")
branches = pd.read_csv("branches.csv")
loans = pd.read_json("loans.json")
support_tickets = pd.read_json("support_tickets.json")

In [ ]:
customers.head()

,customer_id,name,gender,age,city,account_type,join_date
0,C0001,Richard Wilson,M,65,Kimberlyburgh,Savings,2023-08-27
1,C0002,Holly Parker,F,41,Port David,Current,2023-12-08
2,C0003,Megan Alvarez,M,46,West Laurieton,Savings,2022-05-25
3,C0004,Nicholas Stewart,F,39,Amyville,Current,2020-11-30
4,C0005,Douglas Anderson,M,70,New Craigport,Current,2023-01-29

Checking null values

In [ ]:
customers.isnull().sum()

customer_id     0
name            0
gender          0
age             0
city            0
account_type    0
join_date       0
dtype: int64

In [ ]:
accounts.isnull().sum()

customer_id        0
account_balance    0
last_updated       0
dtype: int64

In [ ]:
transactions.isnull().sum()

txn_id         0
customer_id    0
txn_type       0
amount         0
txn_time       0
status         0
dtype: int64

In [ ]:
branches.isnull().sum()

Branch_ID             0
Branch_Name           0
City                  0
Manager_Name          0
Total_Employees       0
Branch_Revenue        0
Opening_Date          0
Performance_Rating    0
dtype: int64

In [ ]:
loans.isnull().sum()

Loan_ID             0
Customer_ID         0
Account_ID          0
Branch              0
Loan_Type           0
Loan_Amount         0
Interest_Rate       0
Loan_Term_Months    0
Start_Date          0
End_Date            0
Loan_Status         0
dtype: int64

In [ ]:
support_tickets.isnull().sum()

Ticket_ID             0
Customer_ID           0
Account_ID            0
Loan_ID               0
Branch_Name           0
Issue_Category        0
Description           0
Date_Opened           0
Date_Closed           0
Priority              0
Status                0
Resolution_Remarks    0
Support_Agent         0
Channel               0
Customer_Rating       0
dtype: int64

In [ ]:
conn = sqlite3.connect("bankdata.db")
cursor = conn.cursor()
def get_conn():
    return sqlite3.connect("bankdata.db", check_same_thread=False)

In [ ]:
conn = get_conn()
customers.to_sql("customers", conn, if_exists="replace", index=False)
accounts.to_sql("accounts", conn, if_exists="replace", index=False)
transactions.to_sql("transactions", conn, if_exists="replace", index=False)
branches.to_sql("branches", conn, if_exists="replace", index=False)
loans.to_sql("loans", conn, if_exists="replace", index=False)
support_tickets.to_sql("support_tickets", conn, if_exists="replace", index=False)

600

In [ ]:
df = pd.read_sql("SELECT * FROM customers", conn)
df

,customer_id,name,gender,age,city,account_type,join_date
0,C0001,Richard Wilson,M,65,Kimberlyburgh,Savings,2023-08-27
1,C0002,Holly Parker,F,41,Port David,Current,2023-12-08
2,C0003,Megan Alvarez,M,46,West Laurieton,Savings,2022-05-25
3,C0004,Nicholas Stewart,F,39,Amyville,Current,2020-11-30
4,C0005,Douglas Anderson,M,70,New Craigport,Current,2023-01-29
...,...,...,...,...,...,...,...
495,C0496,Jennifer Flores,M,50,Mullenland,Savings,2021-04-03
496,C0497,Melissa Martin,M,41,Shermanfurt,Current,2021-12-27
497,C0498,Christopher Johnson,M,69,Nataliemouth,Savings,2022-10-10
498,C0499,Alvin Compton,M,30,Millerstad,Current,2023-06-16
499,C0500,Emily Brooks,M,47,South Louismouth,Savings,2023-10-11

In [ ]:
df1 = pd.read_sql("SELECT * FROM accounts", conn)
df1

    customer_id  account_balance         last_updated
0         C0001        293729.87  2025-05-24 09:46:29
1         C0002        150735.15  2025-05-24 09:46:29
2         C0003        170156.21  2025-05-24 09:46:29
3         C0004        311383.96  2025-05-24 09:46:29
4         C0005         60320.75  2025-05-24 09:46:29
..          ...              ...                  ...
495       C0496        149135.80  2025-05-24 09:46:29
496       C0497        376153.36  2025-05-24 09:46:29
497       C0498        320254.17  2025-05-24 09:46:29
498       C0499        484758.19  2025-05-24 09:46:29
499       C0500        454127.94  2025-05-24 09:46:29

[500 rows x 3 columns]

In [ ]:
df2 = pd.read_sql("SELECT * FROM transactions", conn)
df2

      txn_id customer_id    txn_type    amount             txn_time   status
0     T00001       C0363     deposit  44442.71  2025-02-14 06:26:00  success
1     T00002       C0432     deposit  15737.59  2025-03-27 07:21:21  success
2     T00003       C0084  withdrawal  82150.70  2024-07-31 18:28:06  success
3     T00004       C0067  withdrawal  20313.86  2024-11-11 12:18:47  success
4     T00005       C0485  withdrawal  74536.08  2025-04-15 10:52:59  success
...      ...         ...         ...       ...                  ...      ...
9995  T09996       C0260  withdrawal  54743.72  2024-07-28 08:41:01  success
9996  T09997       C0172    purchase  13087.77  2024-06-23 07:24:30   failed
9997  T09998       C0494  withdrawal  66846.76  2025-02-10 01:47:28   failed
9998  T09999       C0499  withdrawal  90759.88  2024-12-11 04:45:07  success
9999  T10000       C0201  withdrawal  92878.32  2024-06-27 18:07:13   failed

[10000 rows x 6 columns]

In [ ]:
df3 = pd.read_sql("SELECT * FROM branches", conn)
df3

,Branch_ID,Branch_Name,City,Manager_Name,Total_Employees,Branch_Revenue,Opening_Date,Performance_Rating
0,1,"Wang, Mcdonald and Church Branch",Kellitown,Kevin Jones,141,16849288.09,2008-08-01,2
1,2,Crawford-Torres Branch,Angelaburgh,Andrea Steele,39,5822279.32,2015-09-17,1
2,3,Bridges Inc Branch,Johnsonfort,Michael Coleman,195,2114594.03,2012-07-30,3
3,4,Garcia Group Branch,New Kyleberg,Dawn Cooper,144,3390389.63,2018-06-27,2
4,5,"Arroyo, Moore and Freeman Branch",West Coryborough,Samantha Kennedy,42,2771910.11,2012-01-04,5
...,...,...,...,...,...,...,...,...
515,516,Lowery and Sons Branch,Lake Charles,Daniel Hunt,130,6562890.41,2007-06-22,4
516,517,Brooks Group Branch,New Christina,Rodney Browning,19,19078758.01,2021-07-20,1
517,518,Harris-Marshall Branch,Emilymouth,Lorraine Johnson,177,2801634.32,2011-08-18,5
518,519,"Meadows, Taylor and Butler Branch",Port Michael,David Smith,76,17653138.31,2006-05-21,4
519,520,Beltran-Nelson Branch,Juliabury,Richard Singleton,171,19520645.33,2010-09-13,1

In [ ]:
df4 = pd.read_sql("SELECT * FROM loans", conn)
df4

,Loan_ID,Customer_ID,Account_ID,Branch,Loan_Type,Loan_Amount,Interest_Rate,Loan_Term_Months,Start_Date,End_Date,Loan_Status
0,1,1559,2090,Perez Ltd Branch,Personal,259805,12.43,60,2017-07-03,2022-06-07,Active
1,2,1028,2575,Harris-Marshall Branch,Business,3589336,6.75,24,2017-06-14,2019-06-04,Active
2,3,1164,2433,"Taylor, David and Brown Branch",Auto,4621300,9.86,240,2021-08-10,2041-04-27,Closed
3,4,1100,2368,Robertson and Sons Branch,Home,2380953,7.74,120,2016-02-23,2026-01-01,Approved
4,5,1081,2566,"Parrish, Hall and Adams Branch",Home,2268961,12.96,240,2021-01-05,2040-09-22,Approved
...,...,...,...,...,...,...,...,...,...,...,...
548,549,1534,2214,"Potts, Gutierrez and Hancock Branch",Education,2123346,12.40,12,2017-03-26,2018-03-21,Defaulted
549,550,1563,2534,"Cunningham, Lee and Fleming Branch",Education,3314199,11.95,84,2018-08-16,2025-07-10,Active
550,551,1224,2116,Richardson-Morales Branch,Personal,2174941,10.35,84,2017-03-24,2024-02-16,Closed
551,552,1406,2249,"Ross, Hayes and Erickson Branch",Auto,3692011,9.10,36,2023-11-28,2026-11-12,Closed
552,553,1092,2255,"Stewart, Wilson and Dalton Branch",Personal,402265,11.15,240,2022-09-20,2042-06-07,Active

In [ ]:
df5 = pd.read_sql("SELECT * FROM support_tickets", conn)
df5

,Ticket_ID,Customer_ID,Account_ID,Loan_ID,Branch_Name,Issue_Category,Description,Date_Opened,Date_Closed,Priority,Status,Resolution_Remarks,Support_Agent,Channel,Customer_Rating
0,T00001,C0478,A1825,,Gonzalez-Martin Branch,Loan Payment Delay,Client raised loan payment delay.,2017-09-30,2017-10-24,Low,Closed,Card replaced and activated.,Leena Apte,Email,1
1,T00002,C0443,A3583,,Baldwin and Sons Branch,Loan Foreclosure,Client raised loan foreclosure.,2015-04-19,2015-05-12,Critical,In Progress,Card replaced and activated.,Owen Mahajan,In-person,1
2,T00003,C0057,A2616,442,"Porter, Osborne and Mendez Branch",Interest Rate Dispute,Customer reported interest rate dispute.,2016-09-28,2016-10-23,High,Resolved,Loan schedule updated.,Wishi Chhabra,Email,4
3,T00004,C0301,A8786,,"Stafford, Oneal and Williams Branch",Mismatch in Account Statement,Client raised mismatch in account statement.,2019-03-31,2019-04-10,High,Closed,Pending customer verification.,Gabriel Mutti,Email,1
4,T00005,C0238,A3734,,Evans-Mercado Branch,KYC Update Required,System detected kyc update required.,2017-08-11,,Critical,Resolved,Pending customer verification.,Ekani Oza,In-person,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,T00596,C0303,A9594,,Johnson Group Branch,Account Frozen,Customer reported account frozen.,2015-03-08,2015-03-30,Medium,Escalated,Issue resolved successfully.,Chaitaly Vaidya,Mobile App,3
596,T00597,C0480,A5144,,Clark Inc Branch,Interest Rate Dispute,Customer reported interest rate dispute.,2020-01-17,2020-01-26,Medium,In Progress,Issue resolved successfully.,Ekapad Jhaveri,In-person,1
597,T00598,C0270,A7108,427,Murphy-Johnston Branch,Interest Rate Dispute,Client raised interest rate dispute.,2016-04-22,2016-05-13,Critical,Resolved,Loan schedule updated.,Advik Bhagat,In-person,4
598,T00599,C0144,A4959,121,"Herrera, Rollins and Hill Branch",Card Not Working,Customer reported card not working.,2015-02-26,2015-03-25,Low,In Progress,Card replaced and activated.,Wriddhish Sarraf,Phone,2
599,T00600,C0076,A7140,24,Peterson-Graves Branch,EMI Auto-debit Failed,Customer reported emi auto-debit failed.,2023-08-19,2023-09-04,Critical,Escalated,Card replaced and activated.,Ria Ghose,Mobile App,5

In [ ]:
queries = {
   "Q1" : """SELECT c.city, COUNT(DISTINCT c.customer_id) AS total_customers,
    Round(AVG(a.account_balance),2) AS avg_balance
    From customers c
    JOIN accounts a ON c.customer_id=a.customer_id
    GROUP BY c.city
    ORDER BY avg_balance DESC LIMIT 10;""", 

    "Q2" : """SELECT c.account_type, SUM(a.account_balance) AS total_balance
    FROM customers c JOIN accounts a ON c.customer_id=a.customer_id 
    GROUP BY account_type ORDER BY total_balance DESC;""",

    "Q3" : """SELECT c.customer_id, c.name, SUM(a.account_balance) AS total_balance
    from customers c JOIN accounts a ON c.customer_id=a.customer_id
    GROUP BY c.customer_id, c.name ORDER BY total_balance DESC LIMIT 10;""",

    "Q4" : """SELECT c.customer_id, c.name, c.join_date , a.account_balance
    From customers c JOIN accounts a ON c.customer_id=a.customer_id
    WHERE strftime('%Y' , c.join_date)='2023' AND a.account_balance>100000;""",

    "Q5" : """SELECT txn_type, SUM(amount) AS total_amount
    FROM transactions GROUP BY txn_type ORDER BY total_amount DESC;""",

    "Q6" : """SELECT customer_id, COUNT(*) AS failed_count, strftime('%Y-%m', txn_time) AS month
    FROM transactions WHERE lower(trim(status)) = 'failed' 
    GROUP BY customer_id, month HAVING failed_count > 3;""",

    "Q7" : """SELECT a.Branch_Name, SUM(t.amount) AS total_volume
    FROM branches t JOIN accounts a ON t.customer_id=a.customer_id
    GROUP BY a.Branch_Name ORDER BY total_volume DESC LIMIT 5;""",

    "Q8" : """SELECT customer_id, COUNT(*) AS high_value_count 
    FROM transactions WHERE amount >= 200000 
    GROUP BY customer_id HAVING high_value_count >= 5;""",

    "Q9" : """SELECT loan_type, ROUND(AVG(loan_amount),2) AS avg_loan,
    ROUND(AVG(interest_rate),2) AS avg_rate 
    FROM loans GROUP BY loan_type; """,
    
    "Q10" : """SELECT customer_id,count(*) AS active_loans
    FROM loans WHERE loan_status IN ('Approved','Active')
    GROUP BY customer_id HAVING active_loans>1;""",

    "Q11" : """SELECT customer_id, SUM(loan_amount) AS total_loan
    FROM loans WHERE loan_status!='Closed'
    GROUP BY customer_id ORDER BY total_loan DESC LIMIT 5;""",

    "Q12" : """SELECT branch, SUM(account_balance) AS total_balance
    FROM accounts GROUP BY branch ORDER BY total_balance DESC LIMIT 1;""",

    "Q13" : """SELECT b.branch_name,
    COUNT(DISTINCT a.customer_id) AS total_customers,
    COUNT(DISTINCT l.loan_id) AS total_loans,
    ROUND(SUM(a.account_balance),2) AS total_balance
    FROM branches b
    LEFT JOIN accounts a on b.branch_name=a.branch
    LEFT JOIN loans l ON a.customer_id=l.customer_id
    GROUP BY b.branch_name
    ORDER BY total_balance DESC LIMIT 10;""",

    "Q14" : """SELECT issue_category,
    ROUND(AVG(julianday(Date_Closed)-julianday(Date_Opened)),2) AS avg_days,
    COUNT(*) AS total_tickets
    FROM support_tickets
    WHERE Date_Closed!=''
    GROUP BY issue_category ORDER BY avg_days DESC LIMIT 10;""",
    
    "Q15" : """SELECT Support_Agent, COUNT(*) AS resolved_tickets
    FROM support_tickets
    WHERE priority='Critical' AND Customer_Rating>=4
    GROUP BY Support_Agent ORDER BY resolved_tickets DESC LIMIT 5;"""

}

In [ ]:
for q, sql in queries.items():
    print(f"\n{q}:")
    try:
        # quick liveliness test — will raise if conn closed
        conn.execute("SELECT 1")
    except Exception:
        # reconnect and continue
        conn = get_conn()

    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f"Error in {q}: {e}")

conn.close()
print("\nquery executed")

Q1:
                 city  total_customers  avg_balance
0     Margaretchester                1    498739.49
1           Kinghaven                1    498317.41
2           Johnmouth                1    494779.97
3          East Robin                1    494699.91
4          Millerstad                1    484758.19
5          Bobbyhaven                1    482746.37
6      Villanuevafurt                1    481746.58
7  North Christinaton                1    479706.41
8          Bryantport                1    477357.00
9          Amandaberg                1    476044.52

Q2:
  account_type  total_balance
0      Savings    61880483.18
1      Current    61617575.41

Q3:
  customer_id                name  total_balance
0       C0314          Amy Nguyen      498739.49
1       C0011     Carolyn Higgins      498317.41
2       C0111        Lisa Russell      497040.60
3       C0392      Amber Williams      494779.97
4       C0077         Audrey Peck      494699.91
5       C0499       Alvin Compton      484758.19
6       C0338  Sharon Bennett DVM      482746.37
7       C0317     Denise Campbell      481746.58
8       C0220       Jeffrey Smith      481568.14
9       C0146          Ann Crosby      479706.41

Q4:
  customer_id             name   join_date  account_balance
0       C0001   Richard Wilson  2023-08-27        293729.87
1       C0002     Holly Parker  2023-12-08        150735.15
2       C0007   Jasmine Morris  2023-10-09        291736.90
3       C0017  Jesus Davenport  2023-06-07        345239.48
4       C0021    William Jones  2023-04-01        185053.68
5       C0023  Jennifer Hodges  2023-02-11        447170.74
6       C0028       Adam Jones  2023-07-19        133669.64
7       C0032       John Novak  2023-10-29        155480.37
8       C0034    Vanessa Reese  2023-10-29        206241.86
9       C0046   Virginia Ayala  2023-05-15        294020.42

Q5:
       txn_type  total_amount
0       deposit  1.975748e+08
1    withdrawal  1.513873e+08
2      purchase  7.383403e+07
3      transfer  5.059280e+07
4  online fraud  2.382950e+07

Q6:
Empty DataFrame
Columns: [customer_id, failed_count, month]
Index: []

Q7:
Error in Q7: Execution failed on sql 'SELECT a.Branch_Name, SUM(t.amount) AS total_volume
    FROM branches t JOIN accounts a ON t.customer_id=a.customer_id
    GROUP BY a.Branch_Name ORDER BY total_volume DESC LIMIT 5;': no such column: a.Branch_Name

Q8:
Empty DataFrame
Columns: [customer_id, high_value_count]
Index: []

Q9:
   Loan_Type    avg_loan  avg_rate
0       Auto  2399260.98     10.53
1   Business  2793968.87     10.63
2  Education  2393947.70     10.11
3       Home  2344576.66     10.87
4   Personal  2461543.75     10.46

Q10:
   Customer_ID  active_loans
0         1005             2
1         1010             4
2         1020             2
3         1059             2
4         1073             2
5         1088             3
6         1101             2
7         1108             2
8         1123             2
9         1126             2

Q11:
   Customer_ID  total_loan
0         1455    15389458
1         1383    13279523
2         1088    11960853
3         1236    11783260
4         1010    11747032

Q12:
Error in Q12: Execution failed on sql 'SELECT branch, SUM(account_balance) AS total_balance
    FROM accounts GROUP BY branch ORDER BY total_balance DESC LIMIT 1;': no such column: branch

Q13:
Error in Q13: Execution failed on sql 'SELECT b.branch_name,
    COUNT(DISTINCT a.customer_id) AS total_customers,
    COUNT(DISTINCT l.loan_id) AS total_loans,
    ROUND(SUM(a.account_balance),2) AS total_balance
    FROM branches b
    LEFT JOIN accounts a on b.branch_name=a.branch
    LEFT JOIN loans l ON a.customer_id=l.customer_id
    GROUP BY b.branch_name
    ORDER BY total_balance DESC LIMIT 10;': no such column: a.branch

Q14:
                  Issue_Category  avg_days  total_tickets
0               Card Not Working     18.50             16
1  Mismatch in Account Statement     17.90             31
2      Debit Card Delivery Delay     17.81             27
3             UPI Payment Failed     17.46             24
4        Account Closure Request     17.32             31
5                 Account Frozen     17.12             26
6               Loan Foreclosure     16.58             60
7                  Cheque Bounce     16.00             27
8          EMI Auto-debit Failed     15.98             42
9         Online Transfer Failed     15.48             21

Q15:
      Support_Agent  resolved_tickets
0      Owen Mahajan                 7
1  Wriddhish Sarraf                 6
2       Ranveer Roy                 6
3     Chanakya Natt                 5
4     Gabriel Mutti                 4

query executed